# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
programming_language_category = Category.create(name: "Programming Language")
programming_languages_names = [
'actionScript',
'assembly',
'bash',
'BASIC',
'batch',
'C',
'C++',
'C#',
'caml',
'clojure',
'COBOL',
'coffeeScript',
'ColdFusion',
'COMPASS',
'Curl',
'Dart',
'ECMAScript',
'Elixir',
'Elm',
'Emacs Lisp',
'Erlang',
'F',
'F#',
'Flex',
'Fortran',
'Google Apps Script',
'Game Maker Language',
'GameMonkey Script',
'Go',
'Go!',
'GOTRAN',
'GraphTalk',
'Groovy',
'Hack (programming language)',
'Haskell',
'Haxe',
'High Level Assembly',
'HLSL',
'HyperTalk',
'IBM Basic assembly language',
'IBM HAScript',
'IBM Informix-4GL',
'JADE',
'Java',
'JavaScript',
'LaTeX',
'Lava',
'Logo',
'Logtalk',
'LiveScript',
'Lua',
'Maple',
'Objective-C',
'Objective-J',
'OCaml',
'Pascal',
'Perl',
'PostScript',
'PowerShell',
'Processing',
'Processing.js',
'Python',
'QtScript',
'QuakeC',
'Ruby',
'Smalltalk',
'Squeak',
'Squirrel',
'Stateflow',
'Subtext',
'SuperCollider',
'SuperTalk',
'Swift (Apple programming language)',
'TypeScript',
'Turbo C++',
'Unix shell',
'UnrealScript',
'VBA',
'VBScript',
'Verilog',
'VHDL',
'Visual Basic',
'Visual Basic .NET',
'Visual J++',
'Visual J#',
'WebQL',
'Windows PowerShell',
'Z notation'
]
programming_languages_names.each do |skill_name|
  skill = Skill.find_or_create_by(name: skill_name)
  puts "added #{skill.name}"
  skill.categories << programming_language_category
end